### PR TITLE
GP on r

### PR DESCRIPTION
**Pull request by sbfnk**
Work-in-progress version that has a GP on growth for more sensible performance.

Currently working but not optimised.

Ultimately would probably be good to have this as an option but for now I suggest to not merge it.

### CODE REVIEW

**Comment by seabbs** [comment]
So this means the growth rate goes to zero at long lengthscales? A version of this I have tried (and that works with the same impact on performance) is to fit `incidence = inv_logit(inc + sum(GP))` which makes the GP the first difference of incidence.

**Comment by seabbs** [comment]
Example of what I mean: #16

**Comment by seabbs** [comment]
Also added an example of a user settable model (#17). This could be extended with more link options to cover both the logit and log cases.

**Comment by sbfnk** [comment]
> So this means the growth rate goes to zero at long lengthscales? 

Yes, I felt that was a sensible choice and might even give better predictive performance than letting `\delta r -> 0`

**Comment by sbfnk** [comment]
> Also added an example of a user settable difference model (#18). This could be extended with more link options to cover both the logit and log cases.

Ah, that's really elegant. Nice!

**Comment by sbfnk** [comment]
Closing in favour of #16  and #18

**Pull request closed without merging**
