### PR TITLE
Antibodies are tricky...

### PR DESCRIPTION
**Pull request by seabbs**
This PR is a list of changes, code cleaning, and bug fixes made trying to get the antibody model to run..

- Code restyle using tidyverse style guide (automatically when committing - sorry for the PR noise
- Adding weakly informative priors to the antibody model
- Adding documentation and an example to the detectable antibody model
- Increase the width of the prior for the observation error in the antibody model. This was cranked tight for prevalence as expecting low % that are not the case for antibodies. 
- Cleaned up plotting a bit and made some changes to get it to work
- Changed the plotting wrapper to include the faceting for variable so that the lower level functions can be used for other things
- Added a script containing a simple example (i.e not the big loop) to make it easier to debug. 
- Made some more `read_` functions to load last few datasets.

From the example fit (England on a short series of data) things look okay but may breakdown with more data. 

ab
prev

### CODE REVIEW

**Comment by seabbs** [comment]
- 4c63141: Adds example figures and indexing for antibody observations

A full fit has fitting issues. Uncertainy on infections/growth etc. is very spuriously tight suggesting observation model issues.

**Comment by sbfnk** [comment]
This looks great! Am I right in interpreting that adding some priors has stabilised the model? We could try and inform some of them by the literature.

**Comment by seabbs** [comment]
Ah well it has for short time-series and the fitting issues have gone to some degree for longer time-series. Issue remaining has been very poor fits to the antibody data (though without the massive uncertainty you were seeing). Currently looking at a model that splits out waning for infections and those vaccinated to see if that helps (at the moment fitting takes all of time so not quite there)..

**Comment by sbfnk** [comment]
Good call.

**Comment by seabbs** [comment]
So looks like the issue is resolved. Think it may have just been a division where it should have been a multiplication. Added some new switches as debugging to turn off the likelihood for each data source which is helpful for debugging (priors are a little surprising for the antibody model (as in what I think they should look like and what they do look like which may mask another issue). 

Also updated the readme text and put some sample results online. 

See updated README for example fits in England: https://github.com/epiforecasts/inc2prev/tree/tweaks#estimates-from-england

Haven't updated the other estimates or even looked at them so other issues may be lurking.

**Comment by sbfnk** [comment]
Looks great! Do you have some posterior plots of the "biological" parameters to hand? Would be interested in seeing what they look like.

**Comment by sbfnk** [comment]
Ignore, found them.

**Comment by seabbs** [comment]
Yup in readme. Beta is pretty suspicious so may have another none model breaking - issue somewhere.

**Comment by sbfnk** [comment]
Yes I was thinking that re Beta (thanks for finding the `*` vs `/` issue btw). [Another estimate](https://www.medrxiv.org/content/10.1101/2021.07.02.21259897v1) from individual-level dat within the same data set puts it at 0.24. That said, looking at the antibody data the big alpha wave from December last year seems to barely cause a blip in the antibody data. We should probably add a delay to antibody response to the data (or just shift the antibodies 2-3 weeks back in time) but I can't see how that would make a huge difference.

**Comment by seabbs** [comment]
That seems like a nice paper!

**Pull request merged**
